### ISSUE TITLE
Support `JSXElement` and `JSXFragment`

### ISSUE THREAD

**Issue by ovflowd** [Siubaak/sval#107]
When attempting to pass JSX (React component fragments or elements) it fails with `Error: JSXElement isn't implemented` and `Error: JSXFragment isn't implemented`

I assume `sval` doesn't really need to implement said as technically those can be passed through React's JSX runtime (`import { Fragment, jsx, jsxs } from 'react/jsx-runtime';`)

So I wonder what steps would be needed here to support such Node types?

**Comment by Siubaak** [comment]
Well. Actually JSXElement and JSXFragment is not a valid node defination of the ESTree Spec. Even though the parser supports parsing `<div></div>` to JSXElement, it can't be handle by JS.

I think what you should do is, instead of passing a JSX syntax into Sval, you should use some tools like babel/esbuild to transform the JSX syntax to a normal JS call like `React.createElement('div')` first, then pass that call into Sval.

**Comment by Siubaak** [comment]
By the way, I love your Github profile since I just got rickrolled lol

**Comment by ovflowd** [comment]
> Well. Actually JSXElement and JSXFragment is not a valid node defination of the ESTree Spec. Even though the parser supports parsing `<div></div>` to JSXElement, it can't be handled by JS.
> 
> I think what you should do is, instead of passing a JSX syntax into Sval, you should use some tools like babel/esbuild to transform the JSX syntax to a normal JS call like `React.createElement('div')` first, then pass that call into Sval.

Oh yeah, totally, and we were able to circumvent our issue cleverly by doing this: https://github.com/nodejs/nodejs.org/blob/main/apps/site/next.mdx.evaluater.mjs

So closing the issue :D
